apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tileserver.fullname" . }}-gl
  labels:
    app: tileservergl
  {{- include "tileserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gl.replicas }}
  selector:
    matchLabels:
      app: tileservergl
    {{- include "tileserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: tileservergl
      {{- include "tileserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.gl.tileservergl.args | nindent 8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.gl.tileservergl.image.repository }}:{{ .Values.gl.tileservergl.image.tag
          | default .Chart.AppVersion }}
        name: tileservergl
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
          subPath: tileservergl
        - mountPath: /.cache
          name: cache
        - mountPath: /dev/shm
          name: shm
        - mountPath: /tmp
          name: tmp
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "tileserver.fullname" . }}-efs-ap1
      - emptyDir:
          medium: Memory
        name: shm
      - emptyDir: {}
        name: cache
      - emptyDir: {}
        name: tmp